### ISSUE TITLE
Response issue

### ISSUE THREAD

**Issue by mohanad69** [naseemfasal/Paytabs-codeigniter-library#1]
after doing all you mentioned when getting response is empty.
![capture](https://user-images.githubusercontent.com/41144837/43686948-f5bbbe3a-98cd-11e8-91e6-311261fb8af1.PNG)

**Comment by naseemfasal** [comment]
Could you please share screenshot of your executed page ? Try to enable "Display php errors" in your php.ini settings.

**Comment by mohanad69** [comment]
thank you it worked correctly but on the server not on localhost.

**Comment by naseemfasal** [comment]
You are always Welcome.  Don't hesitate to contact me any time for any help here.

**Comment by mohanad69** [comment]
you just need to edit verify_payment in library file and add parameter
$values to it thank you very much

2018-08-08 13:40 GMT+02:00 Naseem Fasal <notifications@github.com>:

**Comment by naseemfasal** [comment]
```
function verify_payment(){
         $values['merchant_email'] = $this->merchant_email;
        $values['secret_key'] = $this->secret_key;
        $values['payment_reference'] = $payment_reference;
        return json_decode($this->post(VERIFY_URL, $values));
    }



```
can you send screenshot of  the corrected code? i can't find any errors here

**Comment by mohanad69** [comment]
just let me check code and i will send it for you .

‫في الأربعاء، 8 أغسطس 2018 في 2:06 م تمت كتابة ما يلي بواسطة ‪Naseem
Fasal‬‏ <‪notifications@github.com‬‏>:‬
